# Use an official Python image
FROM python:3.11-slim

# Copy application files
COPY . /ingest

# Set the working directory
WORKDIR /ingest

RUN apt-get update && \
	apt-get clean

# Install dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Run the script
CMD ["python", "ingest.py"]
