# Use an official Python image
FROM python:3.11-slim

# Copy application files
COPY . /preprocess

# Set the working directory
WORKDIR /preprocess

RUN apt-get update && \
	apt-get clean

# Install dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Run the script
CMD ["python", "convert_to_md.py"]
